name: foobar2000 Component Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build the component
      run: msbuild "foo_lyric_reader/sdk/foobar2000/foo_lyric_reader_project/foo_lyric_reader.sln" /p:Configuration=Release /p:Platform=x86

    - name: Create package directory
      run: mkdir package

    - name: Copy DLL to package directory
      run: cp "foo_lyric_reader/sdk/foobar2000/foo_lyric_reader_project/Release/foo_lyric_reader.dll" "package/"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: foo_lyric_reader_dll
        path: package
